# 基础镜像
FROM openjdk:8-jre


# 挂载目录
VOLUME /home
# 创建目录
RUN mkdir -p /home
# 指定路径
WORKDIR /home
# 复制jar文件到路径
COPY ./jar/word.jar /home/modules-word.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","modules-word.jar"]