# 基础镜像
FROM openjdk:8-jre
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi

COPY ./jar/word.jar /home/ruoyi/word.jar
# 启动word服务
ENTRYPOINT ["java","-jar","word.jar"]